### ISSUE TITLE
JNDI lookups fail

### ISSUE THREAD

**Issue by wkok** [GoogleCloudPlatform/tomcat-runtime#115]
JNDI Resources defined in your app's META-INF/context.xml fails to be looked up due to a javax.naming.NameNotFoundException

I've tracked this down to a problem in the image's server.xml where the Context path="/" definition inside "Host" is causing the app's context.xml to be ignored.

Rebuilding the image with the Context path="/" commented out in server.xml resolves the issue.

**Comment by meltsufin** [comment]
@wkok Thanks for the issue submission.
Removing `path="/"` from `server.xml` might cause the definitions inside there, which are currently only used for session management, to be ignored.
If that's the case, we need a better way to fix the problem.
I wonder if Tomcat by design ingores the app's `context.xml` if there is a context definition in `server.xml`. Something to investigate.

@ChengyuanZhao Can you please take a look?

**Comment by ChengyuanZhao** [comment]
Based on the docs http://tomcat.apache.org/tomcat-8.5-doc/config/context.html it looks maybe we should be using `path=""` instead of `"/"` in `server.xml` to set the "default Context". The page also says "By default, settings from a default context will be used but may be overridden by a setting the same attribute explicitly for the Context.", which sounds like it is the desired behavior (but also sounds like we would first need to change `path="/"` to `path=""` in `server.xml`).

**Comment by meltsufin** [comment]
Sounds good, as long as the sessions stuff still works.

**Comment by ChengyuanZhao** [comment]
Actually, on trying it out, it worked fine if we just take the `&distributed-session-configuration;` out of the `<Context>` element and delete that `<Context>` element completely from server.xml. It looks server.xml's context elements always cause context.xml files to be ignored. 

After moving that distributed sessions line into the outer `<Host>` element, the distributed sessions functionality still works, and I was able to lookup() resources from META-INF/context.xml. I'll make a PR.
