### ISSUE TITLE
Disable tomcat shutdown procedure

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/tomcat-runtime#21]
Tomcat offer the possibility to expose a port to shutdown the instance.

It is recommended to disable this functionality or to restrict the usage to localhost. As the instance instance is not meant to be shutdown it may be preferable to disable this functionality.

**Comment by meltsufin** [comment]
Reading [Tomcat docs](https://tomcat.apache.org/tomcat-8.5-doc/config/server.html), they recommend to leave the port open when started with catalina.sh:

> Note: Disabling the shutdown port works well when Tomcat is started using Apache Commons Daemon (running as a service on Windows or with jsvc on un*xes). It cannot be used when running Tomcat with the standard shell scripts though, as it will prevent shutdown.bat|.sh and catalina.bat|.sh from stopping it gracefully.

I'm not sure if this applies to us because generally the container will be shutdown with SIGTERM, at least in the App Engine Flex environment.

Another thing to note is that we do not expose any ports other than 8080. So, the shutdown port should be automatically protected in docker.

**Comment by cassand** [comment]
Most documentations recommend to disable the shutdown port in production (including official security documentation)

* http://tomcat.apache.org/tomcat-8.0-doc/security-howto.html  server.xml > Server
* https://www.upguard.com/articles/15-ways-to-secure-apache-tomcat-8 third paragraph

I would also think that some web application deployed on the tomcat instance may be able to send http request locally, including to the shutdown tomcat service. 

As the configuration is public we have no way to obfuscate the port/password

**Comment by meltsufin** [comment]
Great point about application sending a request to localhost on any port! :+1:
